name: Deploy Node.js to Azure
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'Project-Beta'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
